# Generated by Django 3.0.3 on 2020-04-07 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_title', models.CharField(max_length=200)),
                ('action_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ApiConfiguration',
            fields=[
                ('api_id', models.IntegerField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=50)),
                ('custom_url', models.CharField(max_length=500)),
                ('long_name', models.CharField(choices=[('1', 'WHO'), ('2', 'World Risk Index'), ('3', 'WorldBank'), ('4', 'Bloomberg')], default='WHO', max_length=200)),
                ('frequency', models.CharField(choices=[('1', 'Hourly'), ('2', 'Daily'), ('3', 'Weekly'), ('4', 'Monthly')], default='Daily', max_length=500)),
                ('short_description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=5)),
                ('country_long', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HeiRulesMonitoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing_procedure', models.CharField(choices=[('1', 'HeiRules CSA 08 Health and Safety'), ('2', 'HeiRules CSA 14 TAX'), ('3', 'HeiRules CSA xx XX')], default='HeiRules CSA xx XX', max_length=200)),
                ('size', models.CharField(choices=[('1', 'Small OPCO'), ('2', 'Medium OPCO'), ('3', 'Large OPCO')], default='Medium OPCO', max_length=200)),
                ('frequency', models.CharField(choices=[('1', 'Weekly'), ('2', 'Monthly'), ('3', 'Quarterly'), ('4', 'Annually')], default='Quarterly', max_length=200)),
                ('way_of_testing', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=50)),
                ('long_description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_short', models.CharField(max_length=50)),
                ('region_long', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_number', models.CharField(max_length=500)),
                ('risk_topic', models.CharField(choices=[('Regulatory changes', 'Regulatory changes'), ('Economic and Political environment', 'Economic and Political environment'), ('Distribution channel', 'Distribution channel'), ('Consumer Preferences', 'Consumer Preferences'), ('Management Capabilities', 'Management Capabilities'), ('Industry Consolidation', 'Industry Consolidation'), ('Health and Safety', 'Health and Safety'), ('Product Safety and Integrity', 'Product Safety and Integrity'), ('Supply Chain Continuity', 'Supply Chain Continuity'), ('Information Securitty', 'Information Securitty'), ('Digital Media', 'Digital Media'), ('Execution and Change Management', 'Execution and Change Management'), ('Reporting', 'Reporting'), ('Non-Compliance', 'Non-Compliance')], default='Regulatory changes', max_length=200)),
                ('risk_response', models.CharField(choices=[('Mitigate', 'Mitigate'), ('Ignore', 'Ignore'), ('Avoid', 'Avoid'), ('Transfer', 'Transfer'), ('Accept', 'Accept'), ('Share', 'Share'), ('Contingecy', 'Contingency'), ('Enhance', 'Enhance'), ('Exploit', 'Exploit')], default='Mitigate', max_length=200)),
                ('risk_classification', models.CharField(choices=[('4', 'Extreme Risk'), ('3', 'High Risk'), ('2', 'Medium Risk'), ('1', 'Low Risk')], default='Low Risk', max_length=200)),
                ('risk_type', models.CharField(choices=[('1', 'Operational'), ('2', 'Strategic'), ('3', 'Compliance')], default='Operational', max_length=200)),
                ('impact_classification', models.CharField(choices=[('4', 'Catastrophic'), ('3', 'Critical'), ('2', 'Moderate'), ('1', 'Negligible')], default='Moderate', max_length=200)),
                ('risk_appetite', models.CharField(choices=[('1', 'Hungry'), ('2', 'Open'), ('3', 'Cautious'), ('4', 'Minimal'), ('5', 'Averse')], default='Averse', max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RiskMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Actions')),
                ('monitoring', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.HeiRulesMonitoring')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Organization')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Risk')),
            ],
        ),
        migrations.CreateModel(
            name='Opco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opco_name', models.CharField(max_length=250)),
                ('opco_size', models.CharField(choices=[('1', 'Small'), ('2', 'Medium'), ('3', 'Large')], default='Medium', max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Country')),
            ],
        ),
        migrations.AddField(
            model_name='heirulesmonitoring',
            name='risk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Risk'),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Region'),
        ),
        migrations.AddField(
            model_name='actions',
            name='risk_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Risk'),
        ),
    ]
