# Generated by Django 3.0.3 on 2020-04-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_risk_risk_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opco',
        ),
    ]
