# Generated by Django 3.0.3 on 2020-04-08 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_opco'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opco',
        ),
    ]
