# Generated by Django 3.0.3 on 2020-04-09 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200409_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heirulesmonitoring',
            name='risk_id',
        ),
        migrations.AddField(
            model_name='heirulesmonitoring',
            name='action_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Actions'),
            preserve_default=False,
        ),
    ]
