# Generated by Django 3.0.3 on 2020-04-09 21:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200409_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='heirulesmonitoring',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heirulesmonitoring',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
