# Generated by Django 3.0.3 on 2020-04-10 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200409_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='risk_id',
        ),
        migrations.RemoveField(
            model_name='heirulesmonitoring',
            name='action_id',
        ),
        migrations.AddField(
            model_name='risk',
            name='action',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Actions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='risk',
            name='monitoring',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.HeiRulesMonitoring'),
            preserve_default=False,
        ),
    ]
