# Generated by Django 3.0.3 on 2020-04-10 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200410_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_long',
            field=models.CharField(choices=[('Netherlands', 'Netherlands'), ('Germany', 'Germany'), ('France', 'France')], default='Netherlands', max_length=250),
        ),
        migrations.CreateModel(
            name='RiskResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Risk')),
            ],
        ),
    ]
