# Generated by Django 3.0.3 on 2020-04-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200410_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='RiskResponse',
        ),
    ]
