# Generated by Django 3.0.3 on 2020-05-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_riskpush'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskpush',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='New', max_length=20),
        ),
    ]
