# Generated by Django 3.1.1 on 2020-09-17 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_riskinput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskinput',
            name='businessProcess',
        ),
        migrations.RemoveField(
            model_name='riskinput',
            name='controlId',
        ),
        migrations.RemoveField(
            model_name='riskinput',
            name='riskName',
        ),
        migrations.AlterField(
            model_name='riskinput',
            name='RiskId',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='RiskAssesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.IntegerField()),
                ('Likelyhood', models.IntegerField()),
                ('relevance', models.CharField(choices=[('Not relevant', 'Not relevant'), ('Relevant', 'Relevant'), ('High importance', 'High importance')], default='Relevant', max_length=20)),
                ('user_id', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.riskinput')),
            ],
        ),
    ]
