# Generated by Django 3.1.1 on 2020-09-17 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200917_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskinput',
            old_name='RiskId',
            new_name='Risk_id',
        ),
    ]
