# Generated by Django 3.1.1 on 2020-09-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200917_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskinput',
            old_name='Risk_id',
            new_name='risk_id',
        ),
        migrations.AddField(
            model_name='riskassesment',
            name='open_entry',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
