# Generated by Django 3.1.1 on 2020-09-17 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20200917_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskassesment',
            old_name='Likelyhood',
            new_name='likelyhood',
        ),
    ]
