# Generated by Django 3.1.1 on 2020-09-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200917_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassesment',
            name='impact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='riskassesment',
            name='likelyhood',
            field=models.IntegerField(null=True),
        ),
    ]
