# Generated by Django 3.1.1 on 2020-09-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200917_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskassesment',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='riskassesment',
            name='open_entry',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='riskassesment',
            name='risk_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
