# Generated by Django 3.1.1 on 2020-09-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20200918_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskinput',
            name='risk_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
